# Generated by Django 3.2.13 on 2023-08-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0002_alter_tarea_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='title',
            new_name='titulo',
        ),
    ]
